#pragma once
#include <windows.h>

#define RXINT_SYMBOLIC_LINK L"\\??\\RxInt"
#define RXINT_DEVICE_NAME L"\\Device\\RxInt"

#define IOCTL_RXINT_START_MONITORING CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_RXINT_STOP_MONITORING CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_RXINT_GET_STATUS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_RXINT_GET_MEMORY_STATS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _RXINT_MONITOR_INFO
{
    ULONG ProcessId;
    WCHAR DumpPath[260];
} RXINT_MONITOR_INFO, *PRXINT_MONITOR_INFO;

typedef struct _RXINT_STATUS_INFO
{
    BOOLEAN IsMonitoring;
    ULONG MonitoredPid;
} RXINT_STATUS_INFO, *PRXINT_STATUS_INFO;

typedef struct _RXINT_MEMORY_STATS
{
    ULONG64 PagedBytes;
    ULONG64 NonPagedBytes;
} RXINT_MEMORY_STATS, *PRXINT_MEMORY_STATS;